version: '3.9'

services:
  db:
    image: postgres:latest
    hostname: '127.0.0.1'
    ports:
      - '5430:5432'
    environment:
      POSTGRES_USER: 1
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: flask_db